#! /usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author   : Alexandre
Created  : 2021-04-07 14:35:18
Modified : 2021-04-07 16:22:13

Comments : starts the HAL gui
"""

# %% IMPORTS

# -- global
import argparse
import sys
import logging
from PyQt5 import QtWidgets

# %% ARGUMENT PARSER
# - init parser
DESCRIPTION_STRING = "Starts HAL, the Atom Locator"
parser = argparse.ArgumentParser(description=DESCRIPTION_STRING)
# - debug mode
parser.add_argument("-d", "--debug", action="store_true", help="debug mode on")
# - parse and analyse
args = parser.parse_args()

# %% LOGGER
# setup format
fmt = "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
# config : default level set to Warning
logging.basicConfig(format=fmt, datefmt="%H:%M:%S", level=logging.WARNING)
# rise level to DEBUG for HAL in debug mode
if args.debug:
    logger = logging.getLogger("HAL")
    logger.setLevel(logging.DEBUG)
    logger.debug("debug mode enabled")

# %% MAIN FUNCTION
from HAL.gui.main import MainWindow


def main(args, argv):
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow(debug=args.debug)
    window.main()
    app.exec_()


# %% RUN
if __name__ == "__main__":
    main(args, sys.argv)
