# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1348, 757)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dayBrowserBox = QtWidgets.QGroupBox(self.centralwidget)
        self.dayBrowserBox.setGeometry(QtCore.QRect(10, 10, 161, 291))
        self.dayBrowserBox.setObjectName("dayBrowserBox")
        self.dayList = QtWidgets.QListWidget(self.dayBrowserBox)
        self.dayList.setGeometry(QtCore.QRect(120, 70, 31, 211))
        self.dayList.setObjectName("dayList")
        self.monthList = QtWidgets.QListWidget(self.dayBrowserBox)
        self.monthList.setGeometry(QtCore.QRect(80, 70, 31, 211))
        self.monthList.setObjectName("monthList")
        self.yearList = QtWidgets.QListWidget(self.dayBrowserBox)
        self.yearList.setGeometry(QtCore.QRect(10, 70, 61, 211))
        self.yearList.setObjectName("yearList")
        self.dateEdit = QtWidgets.QDateEdit(self.dayBrowserBox)
        self.dateEdit.setGeometry(QtCore.QRect(10, 30, 141, 24))
        self.dateEdit.setObjectName("dateEdit")
        self.runBrowserBox = QtWidgets.QGroupBox(self.centralwidget)
        self.runBrowserBox.setGeometry(QtCore.QRect(10, 310, 311, 391))
        self.runBrowserBox.setObjectName("runBrowserBox")
        self.seqList = QtWidgets.QListWidget(self.runBrowserBox)
        self.seqList.setGeometry(QtCore.QRect(160, 30, 141, 321))
        self.seqList.setObjectName("seqList")
        self.runList = QtWidgets.QListWidget(self.runBrowserBox)
        self.runList.setGeometry(QtCore.QRect(10, 30, 141, 321))
        self.runList.setObjectName("runList")
        self.refreshRunListButton = QtWidgets.QPushButton(self.runBrowserBox)
        self.refreshRunListButton.setGeometry(QtCore.QRect(10, 360, 80, 23))
        self.refreshRunListButton.setObjectName("refreshRunListButton")
        self.fitButton = QtWidgets.QPushButton(self.runBrowserBox)
        self.fitButton.setGeometry(QtCore.QRect(100, 360, 80, 23))
        self.fitButton.setObjectName("fitButton")
        self.settingsTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.settingsTabWidget.setGeometry(QtCore.QRect(180, 20, 151, 281))
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 141, 148))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dataTypeComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.dataTypeComboBox.setObjectName("dataTypeComboBox")
        self.verticalLayout.addWidget(self.dataTypeComboBox)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.colorMapComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.colorMapComboBox.setObjectName("colorMapComboBox")
        self.verticalLayout.addWidget(self.colorMapComboBox)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scaleMinEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.scaleMinEdit.setObjectName("scaleMinEdit")
        self.horizontalLayout_2.addWidget(self.scaleMinEdit)
        self.scaleMaxEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.scaleMaxEdit.setObjectName("scaleMaxEdit")
        self.horizontalLayout_2.addWidget(self.scaleMaxEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.settingsTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.settingsTabWidget.addTab(self.tab_2, "")
        self.mainScreen = GraphicsLayoutWidget(self.centralwidget)
        self.mainScreen.setGeometry(QtCore.QRect(340, 10, 771, 541))
        self.mainScreen.setObjectName("mainScreen")
        self.metaDataBox = QtWidgets.QGroupBox(self.centralwidget)
        self.metaDataBox.setGeometry(QtCore.QRect(1120, 10, 191, 701))
        self.metaDataBox.setObjectName("metaDataBox")
        self.metaDataText = QtWidgets.QTextBrowser(self.metaDataBox)
        self.metaDataText.setGeometry(QtCore.QRect(0, 20, 191, 521))
        self.metaDataText.setObjectName("metaDataText")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1348, 20))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.settingsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "HAL"))
        self.dayBrowserBox.setTitle(_translate("mainWindow", "Day browser"))
        self.runBrowserBox.setTitle(_translate("mainWindow", "Run browser"))
        self.refreshRunListButton.setText(_translate("mainWindow", "Refresh"))
        self.fitButton.setText(_translate("mainWindow", "FIT"))
        self.label.setText(_translate("mainWindow", "Data Type"))
        self.label_2.setText(_translate("mainWindow", "Colormap"))
        self.label_3.setText(_translate("mainWindow", "Scale"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.tab), _translate("mainWindow", "Data"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.tab_2), _translate("mainWindow", "FIT"))
        self.metaDataBox.setTitle(_translate("mainWindow", "Meta Data"))
from pyqtgraph import GraphicsLayoutWidget
