# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HAL/gui/ui/plotting_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plottingOptionsWindow(object):
    def setupUi(self, plottingOptionsWindow):
        plottingOptionsWindow.setObjectName("plottingOptionsWindow")
        plottingOptionsWindow.resize(887, 437)
        self.centralwidget = QtWidgets.QWidget(plottingOptionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 871, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.options2DgroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.options2DgroupBox.setObjectName("options2DgroupBox")
        self.horizontalLayout.addWidget(self.options2DgroupBox)
        self.option1DgroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.option1DgroupBox.setObjectName("option1DgroupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.option1DgroupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 411, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.showStdDevCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.showStdDevCheckBox.setObjectName("showStdDevCheckBox")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.showStdDevCheckBox
        )
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cmapComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cmapComboBox.setEditable(False)
        self.cmapComboBox.setObjectName("cmapComboBox")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.cmapComboBox.addItem("")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.cmapComboBox
        )
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.option1DgroupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 210, 415, 150))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.interpolationEnabledLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.interpolationEnabledLabel.setObjectName("interpolationEnabledLabel")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.interpolationEnabledLabel
        )
        self.interpolationEnabledCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.interpolationEnabledCheckBox.setChecked(True)
        self.interpolationEnabledCheckBox.setObjectName("interpolationEnabledCheckBox")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.interpolationEnabledCheckBox
        )
        self.showNodesLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.showNodesLabel.setObjectName("showNodesLabel")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.showNodesLabel
        )
        self.showNodesCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.showNodesCheckBox.setChecked(True)
        self.showNodesCheckBox.setObjectName("showNodesCheckBox")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.showNodesCheckBox
        )
        self.radialFunctionsBasisLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.radialFunctionsBasisLabel.setObjectName("radialFunctionsBasisLabel")
        self.formLayout_3.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.radialFunctionsBasisLabel
        )
        self.radialFunctionsBasisComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.radialFunctionsBasisComboBox.setObjectName("radialFunctionsBasisComboBox")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.radialFunctionsBasisComboBox.addItem("")
        self.formLayout_3.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.radialFunctionsBasisComboBox
        )
        self.epsilonValueLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.epsilonValueLabel.setObjectName("epsilonValueLabel")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.epsilonValueLabel
        )
        self.epsilonValueLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.epsilonValueLineEdit.setObjectName("epsilonValueLineEdit")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.epsilonValueLineEdit
        )
        self.degreeLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.degreeLabel.setObjectName("degreeLabel")
        self.formLayout_3.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.degreeLabel
        )
        self.degreeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.degreeLineEdit.setObjectName("degreeLineEdit")
        self.formLayout_3.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.degreeLineEdit
        )
        self.label_2 = QtWidgets.QLabel(self.option1DgroupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 201, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.option1DgroupBox)
        plottingOptionsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(plottingOptionsWindow)
        self.statusbar.setObjectName("statusbar")
        plottingOptionsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(plottingOptionsWindow)
        QtCore.QMetaObject.connectSlotsByName(plottingOptionsWindow)

    def retranslateUi(self, plottingOptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        plottingOptionsWindow.setWindowTitle(
            _translate("plottingOptionsWindow", "MainWindow")
        )
        self.options2DgroupBox.setTitle(
            _translate("plottingOptionsWindow", "1D plotting options")
        )
        self.option1DgroupBox.setTitle(
            _translate("plottingOptionsWindow", "2D plotting options")
        )
        self.showStdDevCheckBox.setText(
            _translate("plottingOptionsWindow", "show standart deviation")
        )
        self.label.setText(_translate("plottingOptionsWindow", "color map"))
        self.cmapComboBox.setItemText(0, _translate("plottingOptionsWindow", "mako"))
        self.cmapComboBox.setItemText(1, _translate("plottingOptionsWindow", "jet"))
        self.cmapComboBox.setItemText(2, _translate("plottingOptionsWindow", "viridis"))
        self.cmapComboBox.setItemText(3, _translate("plottingOptionsWindow", "plasma"))
        self.cmapComboBox.setItemText(4, _translate("plottingOptionsWindow", "inferno"))
        self.cmapComboBox.setItemText(5, _translate("plottingOptionsWindow", "magma"))
        self.cmapComboBox.setItemText(6, _translate("plottingOptionsWindow", "crest"))
        self.cmapComboBox.setItemText(7, _translate("plottingOptionsWindow", "flare"))
        self.cmapComboBox.setItemText(8, _translate("plottingOptionsWindow", "cividis"))
        self.cmapComboBox.setItemText(
            9, _translate("plottingOptionsWindow", "Spectral")
        )
        self.cmapComboBox.setItemText(
            10, _translate("plottingOptionsWindow", "Spectral_r")
        )
        self.cmapComboBox.setItemText(
            11, _translate("plottingOptionsWindow", "coolwarm")
        )
        self.cmapComboBox.setItemText(12, _translate("plottingOptionsWindow", "bwr"))
        self.cmapComboBox.setItemText(
            13, _translate("plottingOptionsWindow", "seismic")
        )
        self.cmapComboBox.setItemText(
            14, _translate("plottingOptionsWindow", "cubehelix")
        )
        self.cmapComboBox.setItemText(15, _translate("plottingOptionsWindow", "rocket"))
        self.cmapComboBox.setItemText(
            16, _translate("plottingOptionsWindow", "rocket_r")
        )
        self.cmapComboBox.setItemText(17, _translate("plottingOptionsWindow", "Greys"))
        self.cmapComboBox.setItemText(
            18, _translate("plottingOptionsWindow", "Purples")
        )
        self.cmapComboBox.setItemText(19, _translate("plottingOptionsWindow", "Blues"))
        self.cmapComboBox.setItemText(20, _translate("plottingOptionsWindow", "Greens"))
        self.cmapComboBox.setItemText(
            21, _translate("plottingOptionsWindow", "Oranges")
        )
        self.cmapComboBox.setItemText(22, _translate("plottingOptionsWindow", "Reds"))
        self.cmapComboBox.setItemText(23, _translate("plottingOptionsWindow", "YlOrBr"))
        self.cmapComboBox.setItemText(24, _translate("plottingOptionsWindow", "YlOrRd"))
        self.cmapComboBox.setItemText(25, _translate("plottingOptionsWindow", "OrRd"))
        self.cmapComboBox.setItemText(26, _translate("plottingOptionsWindow", "PuRd"))
        self.cmapComboBox.setItemText(27, _translate("plottingOptionsWindow", "RdPu"))
        self.cmapComboBox.setItemText(28, _translate("plottingOptionsWindow", "BuPu"))
        self.cmapComboBox.setItemText(29, _translate("plottingOptionsWindow", "GnBu"))
        self.cmapComboBox.setItemText(30, _translate("plottingOptionsWindow", "PuBu"))
        self.cmapComboBox.setItemText(31, _translate("plottingOptionsWindow", "YlGnBu"))
        self.cmapComboBox.setItemText(32, _translate("plottingOptionsWindow", "PuBuGn"))
        self.cmapComboBox.setItemText(33, _translate("plottingOptionsWindow", "BuGn"))
        self.cmapComboBox.setItemText(34, _translate("plottingOptionsWindow", "YlGn"))
        self.cmapComboBox.setItemText(35, _translate("plottingOptionsWindow", "PiYG"))
        self.cmapComboBox.setItemText(36, _translate("plottingOptionsWindow", "PRGn"))
        self.cmapComboBox.setItemText(37, _translate("plottingOptionsWindow", "BrBG"))
        self.cmapComboBox.setItemText(38, _translate("plottingOptionsWindow", "PuOr"))
        self.cmapComboBox.setItemText(39, _translate("plottingOptionsWindow", "RdGy"))
        self.cmapComboBox.setItemText(40, _translate("plottingOptionsWindow", "RdBu"))
        self.cmapComboBox.setItemText(41, _translate("plottingOptionsWindow", "RdYlBu"))
        self.cmapComboBox.setItemText(42, _translate("plottingOptionsWindow", "RdYlGn"))
        self.interpolationEnabledLabel.setText(
            _translate("plottingOptionsWindow", "enabled")
        )
        self.showNodesLabel.setText(_translate("plottingOptionsWindow", "show nodes"))
        self.radialFunctionsBasisLabel.setText(
            _translate("plottingOptionsWindow", "radial functions basis")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            0, _translate("plottingOptionsWindow", "thin_plate_spline")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            1, _translate("plottingOptionsWindow", "linear")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            2, _translate("plottingOptionsWindow", "cubic")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            3, _translate("plottingOptionsWindow", "quintic")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            4, _translate("plottingOptionsWindow", "multiquadric")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            5, _translate("plottingOptionsWindow", "inverse_multiquadric")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            6, _translate("plottingOptionsWindow", "inverse_quadratic")
        )
        self.radialFunctionsBasisComboBox.setItemText(
            7, _translate("plottingOptionsWindow", "gaussian")
        )
        self.epsilonValueLabel.setText(
            _translate("plottingOptionsWindow", "epsilon value")
        )
        self.epsilonValueLineEdit.setText(_translate("plottingOptionsWindow", "1.0"))
        self.degreeLabel.setText(_translate("plottingOptionsWindow", "degree"))
        self.degreeLineEdit.setText(_translate("plottingOptionsWindow", "None"))
        self.label_2.setText(
            _translate("plottingOptionsWindow", "Smooth interpolation")
        )
